print("Universitas Bina Sarana Informatika".lower())
print("Universitas Bina Sarana Informatika".upper())
print("I love in Python".split())
print("I lova Python".startswith("I"))
print("Saya blajar Python".endswith("on"))
print(' - '.join(['I', 'love', 'you']))
print("Blajar Java di BSI".replace('Java', 'Python'))
